config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  resources :users, only: [:show]
  resources :trips, except: [:destroy]
  get '/about' => 'root#about'
  get '/team' => 'root#team'

  resources :sessions, only: [:new, :create, :destroy]

  get 'sessions/sub_callback' => 'sessions#sub_callback'    # for instagram subscriptions
  post 'sessions/sub_callback' => 'sessions#sub_callback'

  get 'instagram/oauth/connect'   => 'sessions#new'
  get 'oauth/callback'            => 'sessions#create'
  get '/sessions/destroy'         => 'sessions#destroy'

  get 'addvisuals' => 'trips#addvisuals'
  get 'genhashtag' => 'trips#genhashtag'

  get 'showphotos' => 'trips#showphotos'
  get 'clearphotos' => 'trips#clearphotos'

end

app/models/mountain.rb
class Mountain < ActiveRecord::Base
  has_many :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  extend FriendlyId
  friendly_id :hashtag

  has_and_belongs_to_many :users
  validates_uniqueness_of :hashtag
  belongs_to :mountain
  has_many :visuals
  accepts_nested_attributes_for :users

  def self.genhashtag
    verbs=%w(sleeping crying laughing jumping dancing singing feasting sitting coding)
    fruits=%w(orange banana pineapple apple kiwi grape lime mango)
    adjectives=%w(passionate hot friendly lazy loving crazy smart tall fat kind boring)

    return "#{adjectives.sample}#{fruits.sample}#{verbs.sample}"
  end


end
  

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :trips
  has_many :visuals, through: :trips

  #this is just so admins can delete everyything  
  def self.destroy_subs(tag_id=nil)
    if tag_id == nil
      Instagram.delete_subscription(object: "all") #all subs user, locations, tags etc. 
    else
      Instagram.delete_subscription(object: "tag", object_id: tag_id)
    end
  end

  def self.destroy_stuv
    self.destroy_subs
    Trip.destroy_all
    User.destroy_all
    Visual.destroy_all
  end

end

app/models/visual.rb
class Visual < ActiveRecord::Base
  validates_uniqueness_of :standard_url
  belongs_to :trip
  before_create :destroy_extra_visuals

  private
    def destroy_extra_visuals
      Visual.select(:id).limit(1000).destroy_all if Visual.count > 3000
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

private 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def team
  end

  def about
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery :except => [:sub_callback]

  def new
    redirect_to Instagram.authorize_url(:redirect_uri => ENV["IG_CALLBACK"])
  end

  def create
    response = Instagram.get_access_token(params[:code], :redirect_uri => ENV["IG_CALLBACK"])
    session[:access_token] = response.access_token

    if session[:access_token]
      user = User.find_by(ig_id: response.user.id) || User.create( user_name: response.user.username, 
                                                                                                    ig_id: response.user.id, 
                                                                                                    ig_profile_url: response.user.profile_picture)
      session[:user_id] = user.id

      redirect_to new_trip_path

    else
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path #, :notice => "You've successfully logged out."
  end

  def sub_callback
    if params["hub.challenge"]
      render :text => params["hub.challenge"]
    else
      #currently not accepting payloads with more than 1 update, but every recent_media query will capture it regardless of the contents of the update. 
      current_tag = params[:_json][0][:object_id]         # the tag that just popped

      puts "$$$$$$$$$$$CURRENT TAG: #{current_tag}$$$$$$$$$$$$"

      trip_id = Trip.find_by(hashtag: current_tag).id

      response = Instagram.tag_recent_media(current_tag)
      puts response
      response.each do |visual|
        if visual[:location]
          lat=visual[:location][:latitude]
          lng=visual[:location][:longitude]
        else
          lat=27.117813 #put no location photos @ atlantis
          lng=-39.199219
        end

        if visual[:caption]
          caption=visual[:caption][:text]
        else
          caption=nil
        end


        Visual.create(  
          trip_id:        trip_id, 
          media_type:     visual[:type], 
          time_taken:     visual[:created_time], 
          thumbnail_url:  visual[:images][:thumbnail][:url], 
          standard_url:   visual[:images][:standard_resolution][:url], 
          caption:        caption, 
          lat:            lat, 
          lng:            lng,
          username:       visual[:user][:username],
          ig_id:          visual[:user][:id],
          profile_pic:    visual[:user][:profile_picture])

        end
    end
    return true     
  end

end   #class end


# response = Instagram.tag_recent_media(current_tag)
# response=# <Hashie::Mash attribution=nil caption=# <Hashie::Mash created_time="1417902456" from=# <Hashie::Mash full_name="kuruvilla.jimmy" id="1582526975" profile_picture="https://instagramimages-a.akamaihd.net/profiles/anonymousUser.jpg" username="kuruvilla.jimmy"> id="869751301580185912" text="#kindgrapecoding"> comments=# <Hashie::Mash count=0 data=[]> created_time="1417902456" filter="Normal" id="869751301085258039_1582526975" images=# <Hashie::Mash low_resolution=# <Hashie::Mash height=306 url="http://scontent-a.cdninstagram.com/hphotos-xpa1/t51.2885-15/928738_907981165903560_804944057_a.jpg" width=306> standard_resolution=# <Hashie::Mash height=640 url="http://scontent-a.cdninstagram.com/hphotos-xpa1/t51.2885-15/928738_907981165903560_804944057_n.jpg" width=640> thumbnail=# <Hashie::Mash height=150 url="http://scontent-a.cdninstagram.com/hphotos-xpa1/t51.2885-15/928738_907981165903560_804944057_s.jpg" width=150>> likes=# <Hashie::Mash count=0 data=[]> link="http://instagram.com/p/wR-jNAHuE3/" location=# <Hashie::Mash latitude=40.7062028 longitude=-73.8353233> tags=["kindgrapecoding"] type="image" user=# <Hashie::Mash bio="" full_name="kuruvilla.jimmy" id="1582526975" profile_picture="https://instagramimages-a.akamaihd.net/profiles/anonymousUser.jpg" username="kuruvilla.jimmy" website=""> users_in_photo=[]>

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  protect_from_forgery :except => [:show, :new]

  def show
    @trip = Trip.friendly.find(params[:id])
    @lat = @trip.mountain.lat
    @lng = @trip.mountain.lng
    @zoom_level = @trip.mountain.zoom_level
    @visuals = @trip.visuals
  end

  def edit
  end

  def update
  end

  def new
    @trip = Trip.new
   end

  def create
    if params[:trip][:mountain_id]=="" #no mountain entered
      @message="please select a mountain"
    else
      trip = Trip.new(mountain_id: params[:trip][:mountain_id], hashtag: params[:trip][:hashtag])
      trip.users << current_user
      if trip.save
        Instagram.create_subscription("tag", "http://ski-mountain-memories.herokuapp.com/sessions/sub_callback", object_id: trip.hashtag)
        redirect_to trip_path(trip.id) and return
      else
        # JJK: I think this kind of behavior should be handled in the model and then written to ERRORS, 
        # and ERROrs should be in the view
        @message="please select another hashtag"
      end
    end
      redirect_to new_trip_path, notice: @message
    end
    

  def addvisuals
    @trip = Trip.friendly.find(params[:trip_id])
    @visuals = @trip.visuals.all.select {|visual| true}

    @profile_pics = @visuals.collect do |visual| 
      visual.profile_pic if visual.trip_id == @trip.id
    end

  end

  def genhashtag
    @newhashtag=Trip.genhashtag
  end

  def showphotos
  end

  def clearphotos
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @usertrips=current_user.trips.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SkiMountainMemories</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <%= javascript_include_tag 'application' %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>

  <!-- Add mousewheel plugin (this is optional) -->
  <script type="text/javascript" src="/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

  <!-- Add fancyBox -->
  <link rel="stylesheet" href="/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
  <script type="text/javascript" src="/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

  <!-- Optionally add helpers - button, thumbnail and/or media -->
  <link rel="stylesheet" href="/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />
  <script type="text/javascript" src="/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
  <script type="text/javascript" src="/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

  <link rel="stylesheet" href="/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />
  <script type="text/javascript" src="/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<body>

    <div class="container">
      <div class="main-navbar">
        <button class="navbar-button" type="button" >
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        </a>
      </div>
    </div>

    <!-- Links on page -->
    <div class="container">
      <div class="navbar-links">
        <ul class="main-links">
        
        <% if session[:user_id] %>
          <% user = User.find(session[:user_id]) %>
          <li class="main-user"><a href="http://instagram.com/<%= user.user_name %>">
            <img class="img-circle img-responsive" src="<%= user.ig_profile_url %>"></a>
          </li>
          <hr>
          <li><%= link_to "Create a trip", new_trip_path, remote: true%></li>
          <li><%= link_to "My Trips", current_user, remote: true %></li>

          <% if @trip && !@trip.hashtag.nil? %>
            <hr>
            <li id="sharelink">Share this trip</li>
            #<%= @trip.hashtag %><br>

            <hr>
            <li class="trip-buddies">Trip buddies <br></li>
            <% end %>
          <hr>
          <li class="logout-link"><a href="<%= sessions_destroy_path %>">Log Out</a></li>
        <% else %>
          <li><a href="<%= instagram_oauth_connect_path %>">Sign in with Instagram</a></li>
          <% end %>
          <hr>
          <li><%= link_to "About", about_path, remote: true %></li>
          <hr>
          <li><%= link_to "Team", team_path, remote: true %></li>

        </ul>
      </div>
    </div>
    
  <div id="ajax">
    <%= yield %>
  </div>

</body>
</html>

app/views/root/about.html.erb
<div class="container container-fluid about">
<h1>About Ski Mountain Memories (SMM)</h1>
  
<ul class="text-left">
    
<div id="accordion">
<h2>What is it?</h2>
<div class="indent">
A frequent problem while enjoying snow sports is that all the great pictures taken during the trip look very similar due to the surroundings. SMM attempts to provide context for those photographs by using geolocation data pulled from your submissions to Instagram and plotting them on a map. SMM also allows you to share your trip photos and map with friends so that the party you are with can enjoy live updates about the mountain, and friends who are not present can be jealous
</div>

<h2>Why build it?</h2>
<div class="indent">
  Our group frequently encountered the problem of context-less media collected during winter adventures and wanted a way to solve that problem 
</div>

<h2>How does it work?</h2>
<div class="indent">
<ul>
<li>
SMM allows a user to log in using Instagram via OAuth
</li>

<li>
SMM generates an easy to remember hashtag to share with friends and associates the hashtag with a particular trip in our Postgres database
</li>

<li>
SMM uses the Instagram API to create a subscription to that hashtag, and when it recieves a push update to the hashtag, inserts a new media object into the database
</li>

<li>
SMM uses the Google Maps API to draw a map of the particular mountain selected, and Javascript to place and update markers for each of the photos associated with a hashtag
</li>

<li>
SMM can also be used visualize any hashtag's occurences live on a map 
</li>

<li>
For SMM to work users must provide geolocation data when posting to Instagram. Photos without location data are placed at "Atlantis," a location in the Atlantic Ocean
</li>


<li>
SMM is hosted on Heroku (Unicorn web server with New Relic for monitoring), Ruby on Rails powers the server side and JQuery/CSS handles client side interactions
</li>
</ul>
</div>

<h2>Who made it?</h2>
<div class="indent">
SMM is a project built by three students at The Flatiron School's web immersive course in NYC, NY. See our <%= link_to "About", about_path, :target => "_blank" %> page to learn more
</div>

<h2>Are there any features that didn't make it in?</h2>
<div class="indent">
Originally the project was intended to also solve two other problems:
<ol>
<li> 
It's hard to track your friends when on a mountain, and you spend an unreasonable amount of time just communicating where you are to each other. We wanted to run the app pseudo-natively on phones, and send users on the same "trip" each others' location
</li>
<li>
  Some trails are more crowded than others, and your decision to choose one over the other could be informed by person-traffic, if that data was available. One solution was to poll for Instagram/Flickr geolocated photos and to treat increased media activity as increased crowding (say on a ski lift), and then to mark those locations as higher traffic
</li> 
</div>

<h2>Where can I look at your code?</h2>
<div class="indent">
<%= link_to "Follow our project on GitHub", "http://github.com/samvantran/ski-mountain-memories/", :target => "_blank" %>
</div>

<h2>Did you make the snow and the spidery thumbnail effects?</h2>
<div class="indent">
  No. 
  The snow effect is done with CSS and Javascript and the code we used came from 
<%= link_to "TheCodePlayer", "http://thecodeplayer.com/walkthrough/html5-canvas-snow-effect", :target => "_blank" %>. The ability to space our photos with the same geolocation came from <%= link_to "OverlappingMarkerSpiderfier", "https://github.com/jawj/OverlappingMarkerSpiderfier", :target => "_blank" %>

</div>

</div>
</ul>
</div>

app/views/root/about.js.erb
$('#ajax').hide();
$('#ajax').html("<%= escape_javascript(render :template => 'root/about.html.erb') %>");
$('#accordion').accordion({heightStyle: 'panel'});
$('#ajax').fadeIn(550);

clearInterval(timer)

app/views/root/index.html.erb
<div class="container">
  <canvas id="snowfall-canvas"></canvas>
</div>

<script>snow()</script>

app/views/root/team.html.erb
<div class="container container-fluid team">
  <h1>Meet the Team</h1>

  <div class="col-md-4">
    <a href="#"><%= image_tag "blake.jpg" %></a>
    <h3>Blake Deboer</h3>
    <h4>Student @ The Flatiron School</h4>
     <p>
     I've loved to build things for as long as I can remember; I went into real estate development to be at the heart of the building process. While working in real estate, I got great feedback on financial models I built in Excel - my favorite part of the job. Eventually, I decided to find a career that would allow me to focus on those building skills, and give me the opportunity to directly create something.
     </p>

    <p>
    That following spring, I took some classes in code - it was exactly what I was looking for: The means to build something myself, and utilize both logic and creativity. A month later, after trying to teach myself to code on off-hours, I left my job to pursue web development full-time. I took some time off and spent the summer teaching myself Ruby, while teaching kids how to wakeboard in Fire Island. After I got back to the city, I enrolled at the Flatiron School. I've been loving every minute and can't wait to for what's next.
    </p>
    <%= link_to "See my profile at Flatiron People", "http://people.flatironschool.com/profiles/blake-deboer", :target => "_blank" %>
  </div>

  <div class="col-md-4">
    <a href="#"><%= image_tag "sam.jpg" %></a>
    <h3>Sam Tran</h3>
    <h4>Student @ The Flatiron School</h4>
    <p>
      For four years I worked as tech recruiter interacting with software developers on a daily basis. I thought it was so cool that they were able to answer questions with technology and solve problems by writing code.
    </p>
    <p>
      Eventually my curiosity got the best of me and I started to explore what programming was actually like. I plowed through a ton of online resources including Codecademy, Code School, Odin Project, and Harvard's CS50x. 
    </p>
    <p>
      After 12 months of self-study, I applied to Flatiron School to pursue my new-found passion and change my career. Here I am 10 weeks later, building an application that can track pictures from around the world!
    </p>
    <%= link_to "See my profile at Flatiron People", "http://people.flatironschool.com/profiles/sam-tran", :target => "_blank" %>
  </div>
<!-- "http://uploads-registrar-flatironschool-com.s3.amazonaws.com/profiles/photos/production/111/large/20141012_142653.jpg?1417664198" -->
  <div class="col-md-4">
    <a href="#"><%= image_tag "jimmy.jpg" %></a>
    <h3>Jimmy Kuruvilla</h3>
    <h4>Student @ The Flatiron School</h4>
     <p>
       I am of Indian origin, I grew up in Saudi Arabia, and came to the US for college in 2001. I graduated from my combined degree program with a bachelor's degrees in Physics and Environmental Engineering in 2007. From 2007 to 2014 I have lived and worked in NYC as an environmental engineer for a consulting firm on Long Island.
     </p>

       <p>
        I sometimes had extended downtime between projects at my previous position, and I filled it by learning how to program. Python quickly became my go to language for office task scripting, and I saved myself a lot of time with automation scripts. I shared them with coworkers who needed the same routines shortened and CAMPer, PhotoRanger, SpecSorter and Serial Loader were minor hits around the water cooler. Writing those scripts were fun and engaging, but I never thought of it as a potential career. That is, until May of 2014 when I heard about coding bootcamps on the radio.
      </p>

       <p>
        It was obvious to me that if there was a chance to make programming my career, I should attempt it, as I far preferred programming to environmental consulting. I applied to The Flatiron School, and am now working hard to begin my new life as a developer.
     </p>
     <%= link_to "See my profile at Flatiron People", "http://people.flatironschool.com/profiles/jimmy-kuruvilla", :target => "_blank" %>
   </div>
</div>

app/views/root/team.js.erb
$('#ajax').hide();
$('#ajax').html("<%= escape_javascript(render :template => 'root/team.html.erb') %>");
$('#ajax').fadeIn(450);

clearInterval(timer)

app/views/trips/addvisuals.js.erb
var oldVisuals=visuals
var visuals=<%= raw @visuals.to_json%>;

function check(){
  for (i = 0; i < visuals.length; i++) { 
    if (!(vcontains(oldVisuals, visuals[i]))){
      addMarker(visuals[i]);
    }
  }
  
  // for (i = 0; i < visuals.length; i++) { 
  //     addMarker(visuals[i]);
  // }
  
  for (i = 0; i < visuals.length && profile_urls.length < 20; i++) { 
    if ( !( contains(profile_urls, visuals[i].ig_id )) && visuals[i].ig_id !== null ) {
      $('.trip-buddies').append('<a href="http://instagram.com/' + visuals[i].username + '"><img src="' + visuals[i].profile_pic +'" data-toggle="tooltip" data-placement="top" title="' + visuals[i].username + '"></a>');
      profile_urls.push(visuals[i].ig_id);
    }
  }
};

check();



$('[data-toggle="tooltip"]').tooltip()

for (i = 0; i < markers.length; i++) { 
  google.maps.event.addListener(markers[i], 'dblclick', function() {
  $.fancybox({
    'type' : 'iframe',
    href: this.imageUrl
  });     
  }); 

  }

app/views/trips/clearphotos.js.erb
for (var i = 0; i < markers.length; i++) {
  markers[i].setMap(null);
}

clearInterval(timer);
markers = [];

$('#photo-time').html("")

app/views/trips/copytoclipboard.js.erb
copyToClipboard("hi");

app/views/trips/edit.html.erb
<h1>Trips#edit</h1>
<p>Find me in app/views/trips/edit.html.erb</p>



<!-- <a class="fancybox" rel="group" href="http://fancyapps.com/fancybox/demo/1_b.jpg"><img src='https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSBbU1XiZj_pRw5gUrUuReEvcz_QVKs3jtuvZn5FTU3LMM9wakP' alt=""/></a>
<a class="fancybox" rel="group" href="http://fancyapps.com/fancybox/demo/2_b.jpg"><img src='https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSBbU1XiZj_pRw5gUrUuReEvcz_QVKs3jtuvZn5FTU3LMM9wakP' alt=""/></a>
 -->
<a class="fancybox-thumb" rel="fancybox-thumb" href="http://farm9.staticflickr.com/8507/8454547519_f8116520e1_b.jpg" title="Ayvalık, Turkey (Nejdet Düzen)">
  <img src="http://farm9.staticflickr.com/8507/8454547519_f8116520e1_m.jpg" alt="" />
</a>
<a class="fancybox-thumb" rel="fancybox-thumb" href="http://farm8.staticflickr.com/7152/6394238505_c94fdd1d89_b.jpg" title="Sicilian Scratches   erice (italianoadoravel on/off coming back)">
  <img src="http://farm8.staticflickr.com/7152/6394238505_c94fdd1d89_m.jpg" alt="" />
</a>
<a class="fancybox-thumb" rel="fancybox-thumb" href="http://farm9.staticflickr.com/8481/8215602321_69d9939b8b_b.jpg" title="The Trail (Msjunior-Check out my galleries)">
  <img src="http://farm9.staticflickr.com/8481/8215602321_69d9939b8b_m.jpg" alt="" />
</a>
<a class="fancybox-thumb" rel="fancybox-thumb" href="http://farm9.staticflickr.com/8200/8220393833_e52cabfe80_b.jpg" title="Trees (Joerg Marx)">
  <img src="http://farm9.staticflickr.com/8200/8220393833_e52cabfe80_m.jpg" alt="" />
</a>

app/views/trips/genhashtag.js.erb
$('#genhashtag').val("<%= @newhashtag%>") 

app/views/trips/new.html.erb
<div class="notice"><%= flash[:notice] %></div>
<div class="form-container">
  

  <%= form_for @trip do |f| %>

      <h2>where are you going?</h2>
      <%= f.select(:mountain_id, Mountain.all.collect {|m| [m.name, m.id]}, { :include_blank => 'find your favorite spot'}) %>

      <h2>is this a good hashtag for your group?</h2>
      <%= f.text_field :hashtag, value: Trip.genhashtag, id: "genhashtag" %><br>

      <%= f.submit "Let's GO!" %>
    <% end %>

    <%= button_to "new hashtag please", "/genhashtag", method: "get", :remote => true %>  
        
</div>


<div class="container">
  <canvas id="snowfall-canvas"></canvas>
</div>


<script>snow()</script>

app/views/trips/new.js.erb
$('#ajax').hide();
$('#ajax').html("<%= escape_javascript(render :template => 'trips/new.html.erb') %>");
$('#ajax').fadeIn(550);

$('#message').hide();
$('#message').html("<h1><%= session[:message] %></h1>")
$('#message').fadeIn(550);
$('#message').fadeOut(4000);

<% session[:message]=nil %>
clearInterval(timer)

app/views/trips/show.html.erb
<script>     
function markerTimer(){$.get( "/addvisuals", {trip_id: $('#map-canvas').data('trip-id')},"script");}
var timer=setInterval(markerTimer, 1000);
</script>
<div class ="show">
<div><h1 class="orange"><%= @trip.hashtag %></h1></div>

<%= content_tag "div", id: "map-canvas", data: {lat: @lat, lng: @lng, zoom: @zoom_level, visuals: @visuals,  trip_id: @trip.id} do %>
<% end %>
<div><h1 class="orange"><%= trip_url(@trip) %></h1></div>
<%= link_to "Show Photos", showphotos_path, remote: true %>
<%= link_to "Clear Photos", clearphotos_path, remote: true %>
</div>


<div id="photo-time"> </div>

app/views/trips/show.js.erb
function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var lat = $('#map-canvas').data('lat'); 
    var lng = $('#map-canvas').data('lng');
    var zoom_level = $('#map-canvas').data('zoom');
    var visuals = $('#map-canvas').data('visuals');

    var mapOptions = {
      center: new google.maps.LatLng(lat, lng),
      zoom: zoom_level,
      mapTypeId: google.maps.MapTypeId.TERRAIN
    };

    map = new google.maps.Map(mapCanvas, mapOptions); //global

    var iw = new google.maps.InfoWindow();
       //global
       oms = new OverlappingMarkerSpiderfier(map,
         {markersWontMove: true, markersWontHide: true});

    oms.addListener('click', function(marker) {
      iw.setContent(marker.popup);
      iw.open(map, marker);
    });
  

  for (i = 0; i < visuals.length; i++) { 
  addMarker(visuals[i])
}

}//end of initialize

google.maps.event.addDomListener(window, 'load', initialize);    

$('#ajax').hide();
$('#ajax').html("<%= escape_javascript(render :template => 'trips/show.html.erb') %>");
$('#ajax').fadeIn(550);

initialize();

app/views/trips/showphotos.js.erb
  for (i = 0; i < visuals.length; i++) { 
    addMarker(visuals[i])
  }

var timer=setInterval(markerTimer, 1000);

app/views/trips/update.html.erb
<h1>Trips#update</h1>
<p>Find me in app/views/trips/update.html.erb</p>

app/views/users/_usertrips.html.erb
  
<li>
<ul>
<h2><%= link_to  usertrips.hashtag, trip_url(Trip.find(usertrips.id))%></h2>
<h4><%= usertrips.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%d %b. %Y") %></h4>
</ul>
</li>

app/views/users/show.html.erb
<div class="user-container">
<div class="container container-fluid user nobullets">
<%= render partial: "usertrips", collection: @usertrips %>
</div>
</div>

app/views/users/show.js.erb
$('#ajax').hide();
$('#ajax').html("<%= escape_javascript(render :template => 'users/show.html.erb') %>");
$('#ajax').fadeIn(550);

clearInterval(timer)